name       : gsimplecal
version    : 2.1
release    : 5
source     :
    - https://github.com/dmedvinsky/gsimplecal/archive/v2.1.tar.gz : 660cac7333d3507203a008e142e2b8f5dfcf0735b6ccabdd8d3d902b5d2c40e9
homepage   : https://github.com/dmedvinsky/gsimplecal/
license    : BSD-3-Clause
summary    : GGsimplecal is a lightweight calendar applet written in C++ using GTK.
component  : office
builddeps  :
    - pkgconfig(gtk+-3.0)
description: |
    Gsimplecal was intentionally made for use with tint2
    panel in the openbox environment to be launched upon clock click,
    but of course it will work without it. In fact, binding the gsimplecal
    to some hotkey in you window manager will probably make you happy.
    The thing is that when it is started it first shows up, when you run
    it again it closes the running instance. In that way it is very easy
    to integrate anywhere. No need to write some wrapper scripts or
    whatever. Also, you can configure it to not only show the calendar,
    but also display multiple clocks for different world timezones.
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
